### PR TITLE
completing all tests 

### PR DESCRIPTION
**Pull request by antoniomachine**

### CODE REVIEW

**Comment by sdesimone** [comment]
Some failures:

1) BigMLTestFields::test_scenario1
Failed asserting that '000000' matches expected null.

/Users/sergio/Documents/dev/apps/bigml/bigml-php/tests/test_27_fields.php:34

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.

Parse error: parse error in /Users/sergio/Documents/dev/apps/bigml/bigml-php/bigml/predicate.php on line 250

Furthermore, I get the following output:

```
Id does not exist
Couldn\'t find a resource matching the given id. The most probable causes are:

 A typo in the resource's id.
 The resource id cannot be accessed with your credentials.

Double-check your resource and credentials info and retry.
No fields structure was found.

Id does not exist: Couldn't find an instance of 'Project' which matched 'pk=5697cdf99ed233408c0012e7'.
Couldn\'t find a resource matching the given id. The most probable causes are:

 A typo in the resource's id.
 The resource id cannot be accessed with your credentials.

Double-check your resource and credentials info and retry.
Id does not exist
Couldn\'t find a resource matching the given id. The most probable causes are:

 A typo in the resource's id.
 The resource id cannot be accessed with your credentials.

Double-check your resource and credentials info and retry.
No fields structure was found.
```

Are you using hardcoded resource IDs?

**Comment by antoniomachine** [comment]
can you test only this test again ? 

./phpunit.phar test_27_fields.php
PHPUnit 4.1.3 by Sebastian Bergmann.

.
Successfully creating a Fields object
And I create a Fields object from the source with objective column 0
Then the object id is 000000

Time: 1.03 seconds, Memory: 4.00Mb

**Comment by sdesimone** [comment]
it worked!

Now, I am running the full test suite again…

**Comment by sdesimone** [comment]
Still getting errors:

```
php /usr/local/bin/phpunit48 test_18_create_anomaly.php 
Parse error: parse error in /Users/sergio/Documents/dev/apps/bigml/bigml-php/bigml/predicate.php on line 250
```

The same happens with: test_03_local_prediction.php, test_05_compare_predictions.php, test_08_multimodel.php, 11, 12, 13, etc.

Other errors: 

There was 1 error:

```
1) BigMLTestMissingErrors::test_scenario1
Invalid argument supplied for foreach()

/Users/sergio/Documents/dev/apps/bigml/bigml-php/bigml/fields.php:428
/Users/sergio/Documents/dev/apps/bigml/bigml-php/tests/test_19_missing_and_errors.php:57
```

**Comment by antoniomachine** [comment]
it's my fault! I forget to do the synchronize with my last commit, Sorry for inconvenience. :-(

**Comment by sdesimone** [comment]
Would you test it using php 5.5? I still get parse errors in predicate.php (several files -- tried on two different installations):

```
php /usr/local/bin/phpunit48 test_18_create_anomaly.php 
Parse error: parse error in /Users/sergio/Documents/dev/apps/bigml/bigml-php/bigml/predicate.php on line 250
```

I also got this:

```
Id does not exist: Couldn't find an instance of 'Project' which matched 'pk=5698b6ac8a318f4bec003e6c'.
```

but could not trace it down to anything useful...

**Comment by antoniomachine** [comment]
Ok, Inside to_list_rule function i found an error. It must run with php 5.5 now. 
Thanks!

**Comment by sdesimone** [comment]
Success! Merging...

**Pull request merged**
