### PR TITLE
added deepnets

### PR DESCRIPTION
**Pull request by akashenfelter**
Added support for remote and local deepnets, including predictions.

### CODE REVIEW

**Comment by charleslparker** [comment]
Hey Allison, this might be helpful:

https://github.com/bigmlcom/laminar/blob/next/tests/data/regression.json

It's a regression test file in JSON.  Each file has the format "model", with an input model, and "validation", which is a list of inputs and correct outputs.  The catch is that the model format will have slight mismatches to what we provide to end users, but you should be able to finesse it into a proper test.  It's pretty comprehensive.  Let me know if you have any questions.

**Comment by akashenfelter** [comment]
Thanks Charlie! That should be really helpful!

**Comment by sdesimone** [comment]
I am getting the following error when running the tests:

Fatal error: Cannot redeclare parse_terms() (previously declared in /Users/sergio/Documents/dev/bigml/bigml-php/bigml/cluster.php:42) in /Users/sergio/Documents/dev/bigml/bigml-php/bigml/modelfields.php on line 115
PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

**Comment by akashenfelter** [comment]
I'm closing this pull request and going to reopen on a cleaned up feature branch.

**Pull request closed without merging**
