### PR TITLE
update core and tests

### PR DESCRIPTION
**Pull request by antoniomachine**

### CODE REVIEW

**Comment by sdesimone** [comment]
Errors when running the full test suite:

There was 1 failure:

1) BigMLTest::test_scenario4
Failed asserting that 0.31101800000000002 matches expected 0.35566199999999998.

/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_05_compare_predictions.php:413

FAILURES!
Tests: 7, Assertions: 216, Failures: 1.

There were 4 errors:

1) BigMLTest::test_scenario1
file_put_contents(tmp/batch_predictions.csv): failed to open stream: No such file or directory

/Users/sergio/Documents/dev/bigml/prs/bigml-php/bigml/bigml.php:842
/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_06_batch_predictions.php:61

2) BigMLTest::test_scenario2
file_put_contents(tmp/batch_predictions.csv): failed to open stream: No such file or directory

/Users/sergio/Documents/dev/bigml/prs/bigml-php/bigml/bigml.php:842
/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_06_batch_predictions.php:115

3) BigMLTest::test_scenario3
file_put_contents(tmp/batch_predictions_c.csv): failed to open stream: No such file or directory

/Users/sergio/Documents/dev/bigml/prs/bigml-php/bigml/bigml.php:1245
/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_06_batch_predictions.php:167

4) BigMLTest::test_scenario5
file_put_contents(tmp/batch_predictions.csv): failed to open stream: No such file or directory

/Users/sergio/Documents/dev/bigml/prs/bigml-php/bigml/bigml.php:1548
/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_06_batch_predictions.php:267

FAILURES!
Tests: 5, Assertions: 53, Errors: 4.

There was 1 failure:

1) BigMLTest::test_scenario1
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Iris-setosa'
+'68.45974'

/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_07_multimodel_batch_predictions.php:101

FAILURES!
Tests: 1, Assertions: 16, Failures: 1.
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

There was 1 failure:

1) BigMLTest::test_scenario2
Failed asserting that 'Iris-setosa' matches expected 67.585819999999998.

/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_11_multimodel_prediction.php:153

FAILURES!
Tests: 2, Assertions: 29, Failures: 1.
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

There was 1 failure:

1) BigMLTest::test_scenario2
Failed asserting that null matches expected 5.

/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_12_public_model_prediction.php:114

FAILURES!
Tests: 2, Assertions: 22, Failures: 1.
PHPUnit 4.8.21 by Sebastian Bergmann and contributors.

There was 1 failure:

1) BigMLTest::test_scenario1
Failed asserting that false is true.

/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_15_download_dataset.php:51

**Comment by antoniomachine** [comment]
- test_05_compare_predictions.php: 
  The problem is the dev mode. In producction mode is ok. 
- test_06_batch_predictions.php:
  The directory tmp don't exists. I create it when i execute the test if don't exists.
- test_07_multimodel_batch_predictions.php
  The problem is the dev mode. In producction mode is ok. 
- test_15_download_dataset.php:
  the server says: "The dataset export is being processed and will be performed soon". Sometimes is ok. I take a look it
- add new tests, 16 to 20.

**Comment by sdesimone** [comment]
Still 2 failures when running the test suite:

1) BigMLTest::test_scenario1
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'Iris-setosa'
+'68.45974'

/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_07_multimodel_batch_predictions.php:101

1) BigMLTest::test_scenario2
Failed asserting that 'Iris-setosa' matches expected 67.585819999999998.

/Users/sergio/Documents/dev/bigml/prs/bigml-php/tests/test_11_multimodel_prediction.php:153

**Comment by antoniomachine** [comment]
In test_07_multimodel_batch_predictions.php and test_11_multimodel_prediction.php, I should remove the test before with tags ($models = self::$api->list_models("tags__in="+$item["tag"]); ), Now it should work. Thanks

**Pull request merged**
