### PR TITLE
fix memory retention when applying rules in model predictions

### PR DESCRIPTION
**Pull request by sdesimone**
Fixes issue #12.

### CODE REVIEW

**Comment by mmerce** [comment]
Is there any reason for this operatorFunction function to exist? I mean, is it fine in PHP to have a $OPERATOR variable at the beginning of the module and ask every time for its $OPERATOR[$operator]?

**Comment by mmerce** [comment]
So, I think it also works with $OPERATOR defined at the top of the module and using global $OPERATOR inside the `apply` method. i don't see the need for the function at all. Do you?

**Comment by sdesimone** [comment]
I would say that not accessing the global directly is a good thing — that is the only advantage of wrapping it into a function. The operatorFunction maps a string (coming from a JSON) into an operator. The fact that this mapping is hosted in an array is just an implementation detail and could change in the future.

But, thinking about it, I discovered that PHP also supports static, so I made $OPERATOR a static variable — which is surely beneficial since the variable is not private to the function and cannot be used from outside.

**Comment by mmerce** [comment]
Ok, I understand you like static here. Just mentioning that the Predicate class has already a static attribute which I think falls in the same category than this one. Maybe we should decide the same change for both?

On the other hand, I believe your PR addresses the memory leak problem, but not the one I mentioned in Issue #12.

**Comment by sdesimone** [comment]
> On 14 Apr 2017, at 21:14, mmerce <notifications@github.com> wrote:
> Ok, I understand you like static here.
> 
yes, I think it is the correct way. No one can access that array and tamper with it, for example. It can only be used like its wrapping function stipulates — nice… :-) If you had not questioned the initial solution, I would have not come up with this, but now I think it’s good.
> Just mentioning that the Predicate class has already a static attribute which I think falls in the same category than this one. Maybe we should decide the same change for both?
> 
I think we should ask Tony why he decided to have one thing as a private static class member and the other as a function. :-) I think the answer would be that it was what resembled the most your Python implementation. Meaning, there will be plenty of similar cases where the translation to PHP caused some deviations from your code cleanliness … :-)

I would prefer not bringing the function inside of the class. We cannot initialize a static array inline, so we would need to declare it as a static class member, then initialize it in the constructor. I think the code is more readable like it is now, with a function that does the mapping with no relation whatsoever with the class, as it should be IMO.

We could even define an operator class doing the mapping from the operator name to its implementation or its human readable version (which is what those two things do), and this would be even better.

But I would also say that this refactoring is not related to the memory-leak bug… :-)

Shall we create a lower-priority kind of list of things we would like to change in the PHP skill?

> On the other hand, I believe your PR addresses the memory leak problem, but not the one I mentioned in Issue #12 <https://github.com/bigmlcom/bigml-php/issues/12>.
> 

yes, that was an error no my part… sorry...

**Comment by mmerce** [comment]
Well, yes. I'm adding your change as is to solve this issue now, but as we were talking about it I wanted to point out that it's better if we decide one way of doing these things. We can talk about this later in another PR. The only thing that is keeping me now from merging is that the tests don't pass, but that's because the predictions have changed due to the backend changes and we need to adapt the tests. Once they pass, we can publish the patch and keep improving the rest.

**Comment by sdesimone** [comment]
Thanks!

**Pull request merged**
